version: '3'
volumes:
  postgres_data: {}
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - 80:80

